name: go
on: [push]
jobs:

    test:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:

            - name: Set up Go 1.16
              uses: actions/setup-go@v1
              with:
                  go-version: 1.16
              id: go

            - name: Check out code into the Go module directory
              uses: actions/checkout@v1

            - name: Caching modules
              uses: actions/cache@v1
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-aw-${{ hashFiles('**/go.sum') }}

            - name: Get dependencies
              run: |
                  export PATH=$PATH:$(go env GOPATH)/bin
                  go get -u github.com/onsi/ginkgo/ginkgo
                  go get -u github.com/onsi/gomega/...
                  go get -u golang.org/x/lint/golint
                  go get -u github.com/loongy/covermerge
                  go get -u github.com/mattn/goveralls
                  cd $GITHUB_WORKSPACE
                  go mod tidy 
                  go vet ./...
                  golint ./...
            - name: Run tests and report test coverage
              env:
                  COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  export PATH=$PATH:$(go env GOPATH)/bin
                  cd $GITHUB_WORKSPACE
                  CI=true ginkgo --v --race --cover --coverprofile coverprofile.out ./...
                  covermerge \
                    coverprofile.out \
                    dht/coverprofile.out \
                    handshake/coverprofile.out \
                    wire/coverprofile.out
                  goveralls -coverprofile=coverprofile.out -service=github
